### ISSUE TITLE
No body type

### ISSUE THREAD

**Issue by Xsowksi** [KiameV/rimworld-editablebackstories#1]
Hi, i found a bug when some pawns don`t have body type. This bug occured in 1.0 version too, do you have any fixes, because it is pretty annoing. This is caused by this mod for 100%. Pls reply.

**Comment by matshou** [comment]
I guess this was resolved in https://github.com/KiameV/rimworld-editablebackstories/commit/f3447d05eceafdd463e24cb3c26f773992e7e647
